### PR TITLE
Bug/throttling

### LINKED ISSUE #9: Throttling when creating PR is not handled
We should probably wrap all calls to bitbucket to handle throttling

### PR DESCRIPTION
**Pull request by AndyCoveo**
Prevent npm from running if there is no package.json (it would create an unecessary package-lock.json)

Fix #9 : Introduce a httpclient with a retrying strategy when communicating with bitbucket

### CODE REVIEW

File: lib/lure/pr.go [hunk 1]
```diff
@@ -136,18 +143,27 @@ func createPullRequest(auth Authentication, sourceBranch string, destBranch stri
...
 	}
 
 	prRequest.Header.Add("Content-Type", "application/json")
 
 	log.Printf("%v\n", prRequest)
 
-	resp, err := http.DefaultClient.Do(prRequest)
+	client := pester.New()
+	client.MaxRetries = 5
+	client.Backoff = pester.ExponentialBackoff
```
Comment (dreisch-coveo) [inline lib/lure/pr.go]: +1 but what's the initial retry interval?  retrying when you get throttled is kind of dubious unless it starts pretty high....

**Review by dreisch-coveo — APPROVED** [review]

File: lib/lure/pr.go (hunk 1 above)
Comment (AndyCoveo) [reply lib/lure/pr.go]: https://github.com/sethgrid/pester/blob/master/pester.go#L130

Looks like 1..2..4..8..16s

Not sure I can have much impact on it, would you increase the MaxRetries?

Comment (dreisch-coveo) [reply lib/lure/pr.go]: Hard to say. Let's see how this works out I guess

Comment (fredboutin) [reply lib/lure/pr.go]: we were retrying every second before and it was working after a few secs so I guess that should work

File: lib/lure/pr.go [hunk 2]
```diff
@@ -136,18 +143,27 @@ func createPullRequest(auth Authentication, sourceBranch string, destBranch stri
...
+		log.Println("Could not create a pull request")
 		return err
 	}
 
 	prRequest.Header.Add("Content-Type", "application/json")
 
 	log.Printf("%v\n", prRequest)
 
-	resp, err := http.DefaultClient.Do(prRequest)
+	client := pester.New()
```
Comment (fredboutin) [inline lib/lure/pr.go]: Could you reuse the same client instead of initializing one every time?

File: lib/lure/pr.go [hunk 3]
```diff
@@ -136,18 +143,27 @@ func createPullRequest(auth Authentication, sourceBranch string, destBranch stri
...
+	client.MaxRetries = 5
```
Comment (fredboutin) [inline lib/lure/pr.go]: maybe this could be a configuration?

Comment (fredboutin) [reply lib/lure/pr.go]: or at least a const

File: lib/lure/npm.go [hunk 4]
```diff
@@ -15,6 +16,12 @@ import (
 type packageJSON map[string]interface{}
 
 func npmOutdated(path string) []moduleVersion {
+	const packageJSONDefaultFileName = "package.json"
+	if _, err := os.Stat(path + packageJSONDefaultFileName); os.IsNotExist(err) {
```
Comment (fredboutin) [inline lib/lure/npm.go:20]: good idea

**Review by fredboutin — COMMENTED** [review]
GG nice improvement!

File: lib/lure/pr.go [hunk 5]
```diff
@@ -103,15 +101,22 @@ func getPullRequests(auth Authentication, username string, repoSlug string) []Pu
...
-	for !(resp.StatusCode == 200 && resp.StatusCode < 300) {
-		log.Printf("Getting '%s' PR returned %d. Retrying...", prRequest.URL, resp.StatusCode)
-		resp, e = http.DefaultClient.Do(prRequest)
-		time.Sleep(time.Second)
+func getPRRequest(prRequest *http.Request) (*PullRequestList, error) {
+	client := getHTTPClient()
+	resp, err := client.Do(prRequest)
+
+	if err != nil {
+		log.Println("Error getting PR Requests", client.LogString())
```
Comment (dreisch-coveo) [inline lib/lure/pr.go:109]: what's considered an error? e.g. you don' tneed to check status code anymore. or there's no point because we'll just fail to parse it anyway?

**Review by dreisch-coveo — APPROVED** [review]

File: lib/lure/pr.go (hunk 5 above)
Comment (AndyCoveo) [reply lib/lure/pr.go:109]: Well I think we still have to check status code. The retryer allow us to be more resilient to temporary errors, but there are still cases where after all the retries we'll still fail to fetch the PR list.

As you mentioned, at this point I'd rather signify that there was an error instead of returning an empty list. The caller can make the choice to stop or continue from that point on.

**Review by fredboutin — APPROVED** [review]
APPROVE
